# Generated by Django 6.0 on 2025-12-14 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_playbook_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('playbook_type', models.CharField(choices=[('auto_resolve', 'Résolution Automatique'), ('defense', 'Défense contre Attaque'), ('investigation', 'Investigation')], default='defense', max_length=20)),
                ('trigger_keywords', models.TextField(help_text="Mots-clés séparés par des virgules (ex: 'ddos, brute force, injection sql')")),
                ('actions', models.TextField(help_text="Actions à prendre (ex: Bloquer l'IP, Isoler le serveur, etc.)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
