# Generated by Django 6.0 on 2025-12-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_playbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='actions',
            field=models.JSONField(default=list, help_text='Actions à prendre (format JSON)'),
        ),
    ]
