# Generated by Django 6.0 on 2025-12-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alert_options_alert_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolved_by_l2',
            field=models.BooleanField(default=False),
        ),
    ]
