# Generated by Django 6.0 on 2025-12-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alert_resolved_by_l2'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='playbook_executed',
            field=models.BooleanField(default=False),
        ),
    ]
